#!/usr/bin/env python

# Read a .clusters file generated by windowing the human genome
# sample data. Verify that all 'chr1' windows are together,
# that all 'chr2' windows are together, etc.

import sys
import argparse

def get_seq_prefix(seq):
    return seq.split('_')[0]

def main():
    # Parse args
    parser = argparse.ArgumentParser()
    parser.add_argument('clusters')
    args = parser.parse_args()

    # Read clusters file, store a list of lists of seqs
    all_clusters = []
    with open(args.clusters, 'r') as clustfile:
        for line in clustfile:
            if not line:
                # I've seen some blank lines in here...
                continue
            elif line.startswith('#'):
                continue
            fields = line.strip().split()
            all_clusters.append(fields)

    # Verify each list of seqs
    perfect = True
    for cluster in all_clusters:
        # Find all 'chrN' prefixes in this cluster
        prefixes = set()
        for seq in cluster:
            prefix = get_seq_prefix(seq)
            prefixes.add(prefix)
        if len(prefixes) > 1:
            sys.stderr.write("Oh no! Cluster {0} has multiple chromosomes\n".format(cluster))
            perfect = False

    # Print results
    if perfect:
        print("Perfect!")
    else:
        print("Not pefect :(")


##########################

if __name__ == '__main__':
    main()
